### ISSUE TITLE
Customisation of signal handling logs

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-cli#11]
Right now, signal handling logs are printed with go-log format even in a PlainCommand. Maybe it's worth it to allow some customisation of how these logs are printed for PlainCommand at least.

**Comment by smola** [comment]
@erizocosmico Do you think it should be configurable per-command?

**Comment by smola** [comment]
If that is the case, we can just allow optional implementation `HandleSignal(os.Signal)` on any command, to use it together with `ExecuteContext`.

**Comment by erizocosmico** [comment]
And also pass the `context.CancelFunc` in case the user wants to cancel the context
